!/**
 * Highstock JS v12.1.2 (2025-01-09)
 * @module highcharts/indicators/atr
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2024 Sebastian Bochan
 *
 * License: www.highcharts.com/license
 */function(t,r){"object"==typeof exports&&"object"==typeof module?module.exports=r(require("highcharts"),require("highcharts").SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/atr",[["highcharts/highcharts"],["highcharts/highcharts","SeriesRegistry"]],r):"object"==typeof exports?exports["highcharts/indicators/atr"]=r(require("highcharts"),require("highcharts").SeriesRegistry):t.Highcharts=r(t.Highcharts,t.Highcharts.SeriesRegistry)}(this,function(t,r){return function(){"use strict";var e,n={512:function(t){t.exports=r},944:function(r){r.exports=t}},o={};function i(t){var r=o[t];if(void 0!==r)return r.exports;var e=o[t]={exports:{}};return n[t](e,e.exports,i),e.exports}i.n=function(t){var r=t&&t.__esModule?function(){return t.default}:function(){return t};return i.d(r,{a:r}),r},i.d=function(t,r){for(var e in r)i.o(r,e)&&!i.o(t,e)&&Object.defineProperty(t,e,{enumerable:!0,get:r[e]})},i.o=function(t,r){return Object.prototype.hasOwnProperty.call(t,r)};var s={};i.d(s,{default:function(){return v}});var a=i(944),u=i.n(a),h=i(512),c=i.n(h),p=(e=function(t,r){return(e=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(t,r){t.__proto__=r}||function(t,r){for(var e in r)r.hasOwnProperty(e)&&(t[e]=r[e])})(t,r)},function(t,r){function n(){this.constructor=t}e(t,r),t.prototype=null===r?Object.create(r):(n.prototype=r.prototype,new n)}),f=c().seriesTypes.sma,d=u().isArray,g=u().merge;function y(t,r){return Math.max(t[1]-t[2],void 0===r?0:Math.abs(t[1]-r[3]),void 0===r?0:Math.abs(t[2]-r[3]))}var l=function(t){function r(){return null!==t&&t.apply(this,arguments)||this}return p(r,t),r.prototype.getValues=function(t,r){var e,n,o,i,s=r.period,a=t.xData,u=t.yData,h=u?u.length:0,c=[[a[0],u[0]]],p=[],f=[],g=[],l=0,v=1,x=0;if(!(a.length<=s)&&d(u[0])&&4===u[0].length){for(i=1;i<=h;i++)((function(t,r,e,n){var o=r[n],i=e[n];t.push([o,i])})(c,a,u,i),s<v)?(e=i,n=l,l=(o=[a[e-1],(n*(s-1)+y(u[e-1],u[e-2]))/s])[1],p.push(o),f.push(o[0]),g.push(o[1])):(s===v?(l=x/(i-1),p.push([a[i-1],l]),f.push(a[i-1]),g.push(l)):x+=y(u[i-1],u[i-2]),v++);return{values:p,xData:f,yData:g}}},r.defaultOptions=g(f.defaultOptions,{params:{index:void 0}}),r}(f);c().registerSeriesType("atr",l);var v=u();return s.default}()});