!/**
 * Highstock JS v12.1.2 (2025-01-09)
 * @module highcharts/indicators/dema
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2024 Rafał Sebestjański
 *
 * License: www.highcharts.com/license
 */function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(require("highcharts"),require("highcharts").SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/dema",[["highcharts/highcharts"],["highcharts/highcharts","SeriesRegistry"]],e):"object"==typeof exports?exports["highcharts/indicators/dema"]=e(require("highcharts"),require("highcharts").SeriesRegistry):t.Highcharts=e(t.Highcharts,t.Highcharts.SeriesRegistry)}(this,function(t,e){return function(){"use strict";var r,o={512:function(t){t.exports=e},944:function(e){e.exports=t}},n={};function i(t){var e=n[t];if(void 0!==e)return e.exports;var r=n[t]={exports:{}};return o[t](r,r.exports,i),r.exports}i.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return i.d(e,{a:e}),e},i.d=function(t,e){for(var r in e)i.o(e,r)&&!i.o(t,r)&&Object.defineProperty(t,r,{enumerable:!0,get:e[r]})},i.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)};var s={};i.d(s,{default:function(){return v}});var a=i(944),u=i.n(a),c=i(512),h=i.n(c),p=(r=function(t,e){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var r in e)e.hasOwnProperty(r)&&(t[r]=e[r])})(t,e)},function(t,e){function o(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(o.prototype=e.prototype,new o)}),f=h().seriesTypes.ema,d=u().correctFloat,l=u().isArray,y=u().merge,g=function(t){function e(){return null!==t&&t.apply(this,arguments)||this}return p(e,t),e.prototype.getEMA=function(e,r,o,n,i,s){return t.prototype.calculateEma.call(this,s||[],e,void 0===i?1:i,this.EMApercent,r,void 0===n?-1:n,o)},e.prototype.getValues=function(e,r){var o,n,i,s,a,u=r.period,c=[],h=2*u,p=e.xData,f=e.yData,y=f?f.length:0,g=[],v=[],x=[],m=0,_=0,O=-1,b=0;if(this.EMApercent=2/(u+1),!(y<2*u-1)){for(l(f[0])&&(O=r.index?r.index:0),b=(m=t.prototype.accumulatePeriodPoints.call(this,u,O,f))/u,m=0,s=u;s<y+2;s++)s<y+1&&(_=this.getEMA(f,n,b,O,s)[1],c.push(_)),n=_,s<h?m+=_:(s===h&&(b=m/u),_=c[s-u-1],o=this.getEMA([_],i,b)[1],a=[p[s-2],d(2*_-o)],g.push(a),v.push(a[0]),x.push(a[1]),i=o);return{values:g,xData:v,yData:x}}},e.defaultOptions=y(f.defaultOptions),e}(f);h().registerSeriesType("dema",g);var v=u();return s.default}()});