!/**
 * Highstock JS v12.1.2 (2025-01-09)
 * @module highcharts/indicators/disparity-index
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highstock
 *
 * (c) 2010-2024 Rafal Sebestjanski
 *
 * License: www.highcharts.com/license
 */function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(require("highcharts"),require("highcharts").SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/disparity-index",[["highcharts/highcharts"],["highcharts/highcharts","SeriesRegistry"]],e):"object"==typeof exports?exports["highcharts/indicators/disparity-index"]=e(require("highcharts"),require("highcharts").SeriesRegistry):t.Highcharts=e(t.Highcharts,t.Highcharts.SeriesRegistry)}(this,function(t,e){return function(){"use strict";var r,i={512:function(t){t.exports=e},944:function(e){e.exports=t}},n={};function a(t){var e=n[t];if(void 0!==e)return e.exports;var r=n[t]={exports:{}};return i[t](r,r.exports,a),r.exports}a.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return a.d(e,{a:e}),e},a.d=function(t,e){for(var r in e)a.o(e,r)&&!a.o(t,r)&&Object.defineProperty(t,r,{enumerable:!0,get:e[r]})},a.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)};var o={};a.d(o,{default:function(){return m}});var s=a(944),p=a.n(s),u=a(512),c=a.n(u),h=(r=function(t,e){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var r in e)e.hasOwnProperty(r)&&(t[r]=e[r])})(t,e)},function(t,e){function i(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(i.prototype=e.prototype,new i)}),f=c().seriesTypes.sma,d=p().correctFloat,y=p().defined,g=p().extend,l=p().isArray,v=p().merge,x=function(t){function e(){return null!==t&&t.apply(this,arguments)||this}return h(e,t),e.prototype.init=function(){var t=arguments,e=t[1].params,r=e&&e.average?e.average:void 0;this.averageIndicator=c().seriesTypes[r]||f,this.averageIndicator.prototype.init.apply(this,t)},e.prototype.calculateDisparityIndex=function(t,e){return d(t-e)/e*100},e.prototype.getValues=function(t,e){var r=e.index,i=t.xData,n=t.yData,a=n?n.length:0,o=[],s=[],p=[],u=this.averageIndicator,c=l(n[0]),h=u.prototype.getValues(t,e),f=h.yData,d=i.indexOf(h.xData[0]);if(f&&0!==f.length&&y(r)&&!(n.length<=d)){for(var g=d;g<a;g++){var v=this.calculateDisparityIndex(c?n[g][r]:n[g],f[g-d]);o.push([i[g],v]),s.push(i[g]),p.push(v)}return{values:o,xData:s,yData:p}}},e.defaultOptions=v(f.defaultOptions,{params:{average:"sma",index:3},marker:{enabled:!1},dataGrouping:{approximation:"averages"}}),e}(f);g(x.prototype,{nameBase:"Disparity Index",nameComponents:["period","average"]}),c().registerSeriesType("disparityindex",x);var m=p();return o.default}()});