!/**
 * Highstock JS v12.1.2 (2025-01-09)
 * @module highcharts/indicators/ppo
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2024 Wojciech Chmiel
 *
 * License: www.highcharts.com/license
 */function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(require("highcharts"),require("highcharts").SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/ppo",[["highcharts/highcharts"],["highcharts/highcharts","SeriesRegistry"]],e):"object"==typeof exports?exports["highcharts/indicators/ppo"]=e(require("highcharts"),require("highcharts").SeriesRegistry):t.Highcharts=e(t.Highcharts,t.Highcharts.SeriesRegistry)}(this,function(t,e){return function(){"use strict";var r,o={512:function(t){t.exports=e},944:function(e){e.exports=t}},n={};function i(t){var e=n[t];if(void 0!==e)return e.exports;var r=n[t]={exports:{}};return o[t](r,r.exports,i),r.exports}i.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return i.d(e,{a:e}),e},i.d=function(t,e){for(var r in e)i.o(e,r)&&!i.o(t,r)&&Object.defineProperty(t,r,{enumerable:!0,get:e[r]})},i.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)};var a={};i.d(a,{default:function(){return v}});var s=i(944),p=i.n(s),u=i(512),c=i.n(u),h=(r=function(t,e){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var r in e)e.hasOwnProperty(r)&&(t[r]=e[r])})(t,e)},function(t,e){function o(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(o.prototype=e.prototype,new o)}),f=c().seriesTypes.ema,d=p().correctFloat,l=p().extend,y=p().merge,g=p().error,x=function(t){function e(){return null!==t&&t.apply(this,arguments)||this}return h(e,t),e.prototype.getValues=function(e,r){var o,n,i=r.periods,a=r.index,s=[],p=[],u=[];if(2!==i.length||i[1]<=i[0]){g('Error: "PPO requires two periods. Notice, first period should be lower than the second one."');return}var c=t.prototype.getValues.call(this,e,{index:a,period:i[0]}),h=t.prototype.getValues.call(this,e,{index:a,period:i[1]});if(c&&h){var f=i[1]-i[0];for(n=0;n<h.yData.length;n++)o=d((c.yData[n+f]-h.yData[n])/h.yData[n]*100),s.push([h.xData[n],o]),p.push(h.xData[n]),u.push(o);return{values:s,xData:p,yData:u}}},e.defaultOptions=y(f.defaultOptions,{params:{period:void 0,periods:[12,26]}}),e}(f);l(x.prototype,{nameBase:"PPO",nameComponents:["periods"]}),c().registerSeriesType("ppo",x);var v=p();return a.default}()});