!/**
 * Highstock JS v12.1.2 (2025-01-09)
 * @module highcharts/indicators/rsi
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2024 Paweł Fus
 *
 * License: www.highcharts.com/license
 */function(t,r){"object"==typeof exports&&"object"==typeof module?module.exports=r(require("highcharts"),require("highcharts").SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/rsi",[["highcharts/highcharts"],["highcharts/highcharts","SeriesRegistry"]],r):"object"==typeof exports?exports["highcharts/indicators/rsi"]=r(require("highcharts"),require("highcharts").SeriesRegistry):t.Highcharts=r(t.Highcharts,t.Highcharts.SeriesRegistry)}(this,function(t,r){return function(){"use strict";var e,n={512:function(t){t.exports=r},944:function(r){r.exports=t}},i={};function o(t){var r=i[t];if(void 0!==r)return r.exports;var e=i[t]={exports:{}};return n[t](e,e.exports,o),e.exports}o.n=function(t){var r=t&&t.__esModule?function(){return t.default}:function(){return t};return o.d(r,{a:r}),r},o.d=function(t,r){for(var e in r)o.o(r,e)&&!o.o(t,e)&&Object.defineProperty(t,e,{enumerable:!0,get:r[e]})},o.o=function(t,r){return Object.prototype.hasOwnProperty.call(t,r)};var s={};o.d(s,{default:function(){return x}});var a=o(944),u=o.n(a),c=o(512),h=o.n(c),f=(e=function(t,r){return(e=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(t,r){t.__proto__=r}||function(t,r){for(var e in r)r.hasOwnProperty(e)&&(t[e]=r[e])})(t,r)},function(t,r){function n(){this.constructor=t}e(t,r),t.prototype=null===r?Object.create(r):(n.prototype=r.prototype,new n)}),p=h().seriesTypes.sma,d=u().isNumber,g=u().merge;function l(t,r){return parseFloat(t.toFixed(r))}var y=function(t){function r(){return null!==t&&t.apply(this,arguments)||this}return f(r,t),r.prototype.getValues=function(t,r){var e,n,i,o,s,a,u=r.period,c=t.xData,h=t.yData,f=h?h.length:0,p=r.decimals,g=[],y=[],x=[],v=0,m=0,b=r.index,_=1;if(!(c.length<u)){for(d(h[0])?a=h:(b=Math.min(b,h[0].length-1),a=h.map(function(t){return t[b]}));_<u;)(n=l(a[_]-a[_-1],p))>0?v+=n:m+=Math.abs(n),_++;for(i=l(v/(u-1),p),o=l(m/(u-1),p),s=_;s<f;s++)(n=l(a[s]-a[s-1],p))>0?(v=n,m=0):(v=0,m=Math.abs(n)),i=l((i*(u-1)+v)/u,p),e=0===(o=l((o*(u-1)+m)/u,p))?100:0===i?0:l(100-100/(1+i/o),p),g.push([c[s],e]),y.push(c[s]),x.push(e);return{values:g,xData:y,yData:x}}},r.defaultOptions=g(p.defaultOptions,{params:{decimals:4,index:3}}),r}(p);h().registerSeriesType("rsi",y);var x=u();return s.default}()});