name: Bug Report
description: Let us know of an Allsky problem.
title: "[BUG] "
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > If you have a QUESTION, enter a GitHub [Discussion](https://github.com/AllskyTeam/allsky/discussions).  Do NOT create an Issue. 
        > If this is a FEATURE REQUEST, go back a page and select the `Feature Request` template.
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > First look in the GitHub [Issues](https://github.com/AllskyTeam/allsky/issues) and [Discussions](https://github.com/AllskyTeam/allsky/discussions) pages.
        > Most problems have already been reported by other people, so add to their Issue instead of creating a new one.
  - type: input
    id: camera
    attributes:
      label: Camera model
      placeholder: "[enter brand and model]"
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: Operating System
      options:
        - Buster
        - Bullseye
        - Bookworm
        - Not a Pi
    validations:
      required: true
  - type: input
    id: allsky_version
    attributes:
      label: Allsky version
      placeholder: "[see:  ~/allsky/version]"
    validations:
      required: true
  - type: input
    id: pi
    attributes:
      label: "Pi and amount of memory (512 MB, 1, 2, 4, or 8 GB)" 
    validations:
      required: true
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: |
        \- Include a clear and concise description of what the problem is.
        \- Include a screenshot of any error message(s).
        \- Can you reproduce it?  If so, how?
        \- Did any settings or anything else change?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log / configuration files
      description: |
        ATTACH files, do NOT copy/paste them:
        &nbsp;
        Follow the instructions for "Reporting Issues" in the Wiki, then attach `/var/log/allsky.log`.
        &nbsp;
        Attach `~/allsky/config/settings.json`, appending `.txt` to its name first.
        &nbsp;
        If your problem is with an **Allsky Website**, also attach:
          \* `~/allsky/html/allsky/configuration.json` (local Website)
          \* `~/allsky/config/remote_configuration.json` (remote Website)
